CREATE TABLE ResourceItem(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50) NULL,
	[Description] VARCHAR(100) NULL,
	Price DECIMAL(18,2) NULL,
	MeasureType INT NULL,
	MeasureValue DECIMAL(18,2) NULL
)

CREATE TABLE ResourceItemPriceHistory(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50) NULL,
	[Description] VARCHAR(100) NULL,
	Price DECIMAL(18,2) NULL,
	MeasureType INT NULL,
	MeasureValue DECIMAL(18,2) NULL
)